FROM python:3.12-slim

WORKDIR /ETL

COPY . .

ENV TZ=Asia/Taipei

#RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install pandas
RUN pip install requests
RUN pip install matplotlib

CMD [ "bash" ]

